[versions]
atrium = "1.2.0"
kbox = "3.1.0"
junitJupiter = "5.13.1"
nexusPublish="2.0.0"

[libraries]
atrium-fluent = { module = "ch.tutteli.atrium:atrium-fluent", version.ref = "atrium" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junitJupiter" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "junitJupiter" }
kbox = { module = "ch.tutteli.kbox:kbox", version.ref = "kbox" }

[plugins]
nexus-publish = { id = "io.github.gradle-nexus.publish-plugin", version.ref = "nexusPublish" }
